name: "GameTest"

on:
  push:
    branches-ignore:
      - "legacy"
  pull_request:
    branches-ignore:
      - "legacy"

jobs:
  gametest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: npm install
        run: npm install

      - name: tsc
        run: tsc
