name: Check Markdown links
on:
  push:
    paths:
      - '**.md'
    branches-ignore:
      - "legacy"
  pull_request:
    paths:
      - '**.md'
    branches-ignore:
      - "legacy"

permissions:
  contents: read

jobs:
  lint-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.14
